HDF5 C++ API: H5::EnumType Class Reference
H5::EnumType Class Reference
EnumType is a derivative of a DataType and operates on HDF5 enum datatypes.
#include <H5EnumType.h>
Public Member Functions
EnumType (size_t size)
Creates an empty enumeration datatype given a size, in bytes.
EnumType (const DataSet &dataset)
Gets the enum datatype of the specified dataset.
EnumType (const IntType &data_type)
Creates a new enum datatype based on an integer datatype.
EnumType (const H5Location &loc, const char *name)
Creates an EnumType instance by opening an HDF5 enum datatype given its name, provided as a C character string.
EnumType (const H5Location &loc, const H5std_string &name)
Creates an EnumType instance by opening an HDF5 enum datatype given its name, provided as an H5std_string.
virtual DataType * decode () const
Returns an EnumType object via DataType* by decoding the binary object description of this type.
Exceptions
H5::DataTypeIException.
int getNmembers () const
Returns the number of members in this enumeration datatype.
int getMemberIndex (const char *name) const
Returns the index of a member in this enumeration datatype.
int getMemberIndex (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of argument name.
void getMemberValue (unsigned memb_no, void *value) const
Retrieves the value of a member in this enumeration datatype, given the member's index.
void insert (const char *name, void *value) const
Inserts a new member to this enumeration datatype.
void insert (const H5std_string &name, void *value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of argument name.
H5std_string nameOf (void *value, size_t size) const
Returns the symbol name corresponding to a specified member of this enumeration datatype.
void valueOf (const char *name, void *value) const
Retrieves the value corresponding to a member of this enumeration datatype, given the member's name.
void valueOf (const H5std_string &name, void *value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of argument name.
virtual H5std_string fromClass () const
Returns this class name.
EnumType ()
Default constructor: Creates a stub datatype.
EnumType (const hid_t existing_id)
Creates an EnumType object using the id of an existing datatype.
EnumType (const EnumType &original)
Copy constructor: makes a copy of the original EnumType object.
virtual ~EnumType ()
Properly terminates access to this enum datatype.
Public Member Functions inherited from H5::DataType
DataType (const H5T_class_t type_class, size_t size)
Creates a object given its class and size.
DataType (const DataType &original)
Copy constructor: makes a copy of the original DataType object.
DataType (const PredType &pred_type)
Creates a DataType instance using a predefined type.
DataType (const H5Location &loc, const char *name)
Creates a DataType instance by opening an HDF5 datatype given its name as a char*.
DataType (const H5Location &loc, const H5std_string &name)
Creates a DataType instance by opening an HDF5 datatype given its name as an H5std_string.
DataType (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT)
Given a reference, ref, to an hdf5 group, creates a DataType object.
DataType (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT)
Given a reference, ref, to an hdf5 group, creates a DataType object.
virtual void close ()
Closes the datatype if it is not a predefined type.
void copy (const DataType &like_type)
Copies an existing datatype to this datatype object.
void copy (const DataSet &dset)
Copies the datatype of the given dataset to this datatype object.
void encode ()
Creates a binary object description of this datatype.
Exceptions
H5::DataTypeIException.
H5T_class_t getClass () const
Returns the datatype class identifier.
void commit (const H5Location &loc, const char *name)
Commits a transient datatype to a file, creating a new named datatype.
void commit (const H5Location &loc, const H5std_string &name)
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
bool committed () const
Determines whether a datatype is a named type or a transient type.
H5T_conv_t find (const DataType &dest, H5T_cdata_t **pcdata) const
Finds a conversion function that can handle a conversion from this datatype to the specified datatype, dest.
void convert (const DataType &dest, size_t nelmts, void *buf, void *background, const PropList &plist=PropList::DEFAULT) const
Converts data from this datatype to the specified datatypes.
DataType & operator= (const DataType &rhs)
Assignment operator.
bool operator== (const DataType &compared_type) const
Compares this DataType against the given one to determines whether the two objects refer to the same actual datatype.
void lock () const
Locks a datatype, making it read-only and non-destructible.
size_t getSize () const
Returns the size of a datatype.
DataType getSuper () const
Returns the base datatype from which a datatype is derived.
void registerFunc (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Registers the specified conversion function.
void registerFunc (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void unregister (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Removes a conversion function from all conversion paths.
void unregister (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void setTag (const char *tag) const
Tags an opaque datatype.
void setTag (const H5std_string &tag) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
H5std_string getTag () const
Gets the tag associated with an opaque datatype.
bool detectClass (H5T_class_t cls) const
Checks whether a datatype contains (or is) a certain type of datatype.
bool isVariableStr () const
Check whether this datatype is a variable-length string.
PropList getCreatePlist () const
Returns a copy of the property list, which is for datatype creation.
DataType (const hid_t type_id)
Creates a datatype using an existing datatype's id.
DataType ()
Default constructor: Creates a stub datatype.
bool hasBinaryDesc () const
Determines whether this datatype has a binary object description.
Exceptions
H5::DataTypeIException.
virtual hid_t getId () const
Get the id of this datatype.
virtual ~DataType ()
Properly terminates access to this datatype.
Public Member Functions inherited from H5::H5Object
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Deprecated - replaced by H5Object::createAttribute.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Deprecated - replaced by H5Object::createAttribute.
Attribute openAttribute (const char *name) const
Deprecated - replaced by H5Object::openAttribute.
Attribute openAttribute (const H5std_string &name) const
Deprecated - replaced by H5Object::openAttribute.
Attribute openAttribute (const unsigned int idx) const
Deprecated - replaced by H5Object::openAttribute.
bool attrExists (const char *name) const
Deprecated - replaced by H5Object::attrExists()
bool attrExists (const H5std_string &name) const
Deprecated - replaced by H5Object::attrExists()
void renameAttr (const char *oldname, const char *newname) const
Deprecated - replaced by H5Object::renameAttr()
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
Deprecated - replaced by H5Object::renameAttr()
void removeAttr (const char *name) const
Deprecated - replaced by H5Object::removeAttr()
void removeAttr (const H5std_string &name) const
Deprecated - replaced by H5Object::removeAttr()
int getNumAttrs () const
ssize_t getObjName (char *obj_name, size_t buf_size=0) const
ssize_t getObjName (H5std_string &obj_name, size_t len=0) const
H5std_string getObjName () const
Public Member Functions inherited from H5::H5Location
bool nameExists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool nameExists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which this HDF5 object belongs.
void getObjectInfo (H5O_info_t *oinfo) const
Retrieve information about an object, specified by location.
Exceptions
H5::LocationException.
void getObjectInfo (const char *name, H5O_info_t *oinfo, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieve information about an object, specified by name.
Exceptions
H5::LocationException.
void getObjectInfo (const H5std_string &name, H5O_info_t *oinfo, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieve information about an object, specified by name.
Exceptions
H5::LocationException.
int getNumAttrs () const
Deprecated - replaced by H5Object::getNumAttrs()
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
unsigned objVersion () const
Returns the header version of this HDF5 object.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
void dereference (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT)
Dereferences a reference into an HDF5 object, given an attribute.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Retrieves a dataspace with the region pointed to selected.
hid_t openObjId (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Opens an object without knowing the object type.
hid_t openObjId (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It takes a reference to a H5std_string for the object's path.
void closeObjId (hid_t obj_id) const
Closes an object, which was opened with H5Location::openObjId.
virtual int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
Protected Member Functions inherited from H5::H5Location
virtual ~H5Location ()
Noop destructor.
Constructor & Destructor Documentation
H5::EnumType::EnumType (size_t size)
Parameters
size - IN: Number of bytes in the datatype to create
Exceptions
H5::DataTypeIException
H5::EnumType::EnumType (const DataSet & dataset)
Parameters
dataset - IN: Dataset that this enum datatype associates with
Exceptions
H5::DataTypeIException
References H5::DataSet::getId().
H5::EnumType::EnumType (const IntType & data_type)
Parameters
data_type - IN: Base datatype
Exceptions
H5::DataTypeIException
References H5::DataType::getId().
H5::EnumType::EnumType (const H5Location & loc, const char * type_name)
Parameters
loc - IN: Location of the type
type_name - IN: Enum datatype name
Exceptions
H5::DataTypeIException
H5::EnumType::EnumType (const H5Location & loc, const H5std_string & type_name)
Parameters
loc - IN: Location of the type
type_name - IN: Enum datatype name
Exceptions
H5::DataTypeIException
H5::EnumType::EnumType ()
Referenced by decode().
H5::EnumType::EnumType (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing datatype
Exceptions
H5::DataTypeIException
H5::EnumType::EnumType (const EnumType & original)
H5::EnumType::~EnumType () virtual
Member Function Documentation
DataType * H5::EnumType::decode () const virtual
Reimplemented from H5::DataType.
References EnumType().
virtual H5std_string H5::EnumType::fromClass () const inline virtual
Reimplemented from H5::DataType.
int H5::EnumType::getMemberIndex (const char * name) const
Parameters
name - IN: Name of the queried member
Returns
Index of the member if it exists. Index will have the value between 0 and N-1, where N is the value returned by the member function EnumType::getNmembers.
Exceptions
H5::DataTypeIException
Referenced by getMemberIndex().
int H5::EnumType::getMemberIndex (const H5std_string & name) const
References getMemberIndex().
void H5::EnumType::getMemberValue (unsigned memb_no, void * value) const
Parameters
memb_no - IN: Index of the queried member
value - OUT: Pointer to the retrieved value
Exceptions
H5::DataTypeIException
int H5::EnumType::getNmembers () const
Returns
Number of members
Exceptions
H5::DataTypeIException
void H5::EnumType::insert (const char * name, void * value) const
Parameters
name - IN: Name of the new member
value - IN: Pointer to the value of the new member
Exceptions
H5::DataTypeIException
Referenced by insert().
void H5::EnumType::insert (const H5std_string & name, void * value) const
References insert().
H5std_string H5::EnumType::nameOf (void * value, size_t size) const
Parameters
value - IN: Pointer to the value of the enum datatype
size - IN: Size for the name
Exceptions
H5::DataTypeIException
void H5::EnumType::valueOf (const char * name, void * value) const
Parameters
name - IN: Name of the queried member
value - OUT: Pointer to the retrieved value
Exceptions
H5::DataTypeIException
Referenced by valueOf().
void H5::EnumType::valueOf (const H5std_string & name, void * value) const
References valueOf().
The documentation for this class was generated from the following files:
H5EnumType.h
H5EnumType.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois